// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace mvc.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mvc.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordsalt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(256),
                            IsDeleted = false,
                            PasswordHash = "76EFBFBD2D5CEFBFBD375A7402EFBFBDD9AF2FEFBFBDEFBFBD43EFBFBDEFBFBDEFBFBDDBBB033FEFBFBD48EFBFBD2E40EFBFBD09EFBFBD06",
                            PasswordSalt = "00000000-0000-0000-0000-000000000000",
                            UserId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(358),
                            IsDeleted = false,
                            PasswordHash = "76EFBFBD2D5CEFBFBD375A7402EFBFBDD9AF2FEFBFBDEFBFBD43EFBFBDEFBFBDEFBFBDDBBB033FEFBFBD48EFBFBD2E40EFBFBD09EFBFBD06",
                            PasswordSalt = "00000000-0000-0000-0000-000000000000",
                            UserId = 2,
                            Username = "nv01"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(397),
                            IsDeleted = false,
                            PasswordHash = "76EFBFBD2D5CEFBFBD375A7402EFBFBDD9AF2FEFBFBDEFBFBD43EFBFBDEFBFBDEFBFBDDBBB033FEFBFBD48EFBFBD2E40EFBFBD09EFBFBD06",
                            PasswordSalt = "00000000-0000-0000-0000-000000000000",
                            UserId = 3,
                            Username = "nv02"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(437),
                            IsDeleted = false,
                            PasswordHash = "76EFBFBD2D5CEFBFBD375A7402EFBFBDD9AF2FEFBFBDEFBFBD43EFBFBDEFBFBDEFBFBDDBBB033FEFBFBD48EFBFBD2E40EFBFBD09EFBFBD06",
                            PasswordSalt = "00000000-0000-0000-0000-000000000000",
                            UserId = 4,
                            Username = "nv03"
                        });
                });

            modelBuilder.Entity("mvc.Domain.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parentId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(558),
                            IsDeleted = false,
                            Name = "Quản lý bán hàng",
                            Path = "sale"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(559),
                            IsDeleted = false,
                            Name = "Quản lý nội dung",
                            Path = "content"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(561),
                            IsDeleted = false,
                            Name = "Quản lý nhân sự",
                            Path = "hr"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(562),
                            IsDeleted = false,
                            Name = "Quản lý hệ thống",
                            Path = "system"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(565),
                            IsDeleted = false,
                            Name = "Menu",
                            ParentId = 4,
                            Path = "menu"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(567),
                            IsDeleted = false,
                            Name = "Quyền",
                            ParentId = 4,
                            Path = "role"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(568),
                            IsDeleted = false,
                            Name = "Quyền",
                            ParentId = 4,
                            Path = "permission"
                        });
                });

            modelBuilder.Entity("mvc.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(504),
                            IsDeleted = false,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(506),
                            IsDeleted = false,
                            Name = "CONTENT CREATOR"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(507),
                            IsDeleted = false,
                            Name = "SALE"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(508),
                            IsDeleted = false,
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("mvc.Domain.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menuId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(595),
                            IsDeleted = false,
                            MenuId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(597),
                            IsDeleted = false,
                            MenuId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(598),
                            IsDeleted = false,
                            MenuId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(599),
                            IsDeleted = false,
                            MenuId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(601),
                            IsDeleted = false,
                            MenuId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(602),
                            IsDeleted = false,
                            MenuId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(603),
                            IsDeleted = false,
                            MenuId = 3,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("mvc.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Long Biên",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 53, DateTimeKind.Local).AddTicks(9753),
                            FullName = "Admin",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Đông",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 53, DateTimeKind.Local).AddTicks(9766),
                            FullName = "Nhân viên CC01",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hai Bà Trưng",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 53, DateTimeKind.Local).AddTicks(9767),
                            FullName = "Nhân viên SALE02",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "Thanh Xuân",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 53, DateTimeKind.Local).AddTicks(9768),
                            FullName = "Nhân viên HR03",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("mvc.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(532),
                            IsDeleted = false,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(533),
                            IsDeleted = false,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(534),
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 6, 14, 0, 11, 1, 54, DateTimeKind.Local).AddTicks(535),
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("mvc.Domain.Account", b =>
                {
                    b.HasOne("mvc.Domain.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("mvc.Domain.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mvc.Domain.Menu", b =>
                {
                    b.HasOne("mvc.Domain.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("mvc.Domain.RoleMenu", b =>
                {
                    b.HasOne("mvc.Domain.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc.Domain.Role", "Role")
                        .WithMany("RoleControllers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("mvc.Domain.UserRole", b =>
                {
                    b.HasOne("mvc.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mvc.Domain.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("mvc.Domain.Role", b =>
                {
                    b.Navigation("RoleControllers");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("mvc.Domain.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
